code_base/Anarde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home', login_required(TemplateView.as_view(template_name="home.html"))),
    path('location/', include('location.urls')),
    path('survey/', include('survey_form.urls')),
    path('domain/', include('domain.urls')),
    path('funders/', include('funders.urls')),
    path('report/', include('report.urls', namespace='report')),

]

code_base/accounts/urls.py
from django.conf.urls import url
from django.urls import path, include
from accounts import views
from django.contrib.auth.decorators import login_required



urlpatterns = [

    path('register/',views.register_view, name='register'),
    path('account_create/',views.account_create, name='account_create'),
    path('account_update/<int:pk>',views.account_update, name='account_update'),
    path('account_list', views.account_list.as_view(), name='account_list'),
    path('get_user_list_for_datatable',views.get_user_list_for_datatable, name='get_user_list_for_datatable'),



]

code_base/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

CHOICES= [
    ('Admin', 'Admin'),
    ('Anarde_user', 'Anarde user'),
    ('Anganwadi_worker', 'Anganwadi worker'),
    ('Funder', 'Funder'),
    ]

class UsersRegisterForm(UserCreationForm):

    groups = forms.CharField(label='User role', widget=forms.Select(choices=CHOICES))
    class Meta:
        model = User
        fields = ('username', 'groups', 'password1', 'password2', )

class UpdateUserForm(forms.ModelForm):
    User_CHOICES = [
        ('1', 'True'),
        ('0', 'False'),
    ]
    is_active = forms.CharField(label='Active_status', widget=forms.Select(choices=User_CHOICES))
    class Meta:
         model = User
         fields = ('username', 'is_active')

code_base/accounts/views.py
from django.views.generic import UpdateView
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from .forms import UsersRegisterForm, UpdateUserForm
from django.contrib.auth.decorators import login_required
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.core import serializers

# Create your views here.

def register_view(request):
    if request.method == 'POST':
        form = UsersRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            group = form.cleaned_data.get('groups')
            if group != "Admin":
                user.is_active = False
                user.save()
            else:
                user.is_superuser = True
                user.is_staff = True
                user.save()

            group = Group.objects.get(name=group)
            user.groups.add(group)
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/accounts/login')
        else:
            print(form.errors)
    else:
        form = UsersRegisterForm()
    return render(request, 'signup.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def account_create(request, template_name='account_create.html'):
    if request.method == 'POST':
        form = UsersRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            group = form.cleaned_data.get('groups')
            if group != "Admin":
                user.save()
            else:
                user.is_superuser = True
                user.is_staff = True
                user.save()

            group = Group.objects.get(name=group)
            user.groups.add(group)
            return redirect('/accounts/account_list')
        else:
            print(form.errors)
    else:
        form = UsersRegisterForm()
    return render(request, template_name, {'form': form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def account_update(request, pk, template_name='account_update.html'):
    UserForUpdate = get_object_or_404(User, pk=pk)

    #  Fetch names of all groups where user is part
    groupName = ''
    userGroups = UserForUpdate.groups.all()
    for userGroup in userGroups:
        groupName = groupName + userGroup.name

    form = UpdateUserForm(instance=UserForUpdate)
    if request.method == 'POST':
        print(request.POST)
        if 'cancel' in request.POST:
            print('cancelling request')
            return redirect('/account/account_list/' + str(pk))

        form = UpdateUserForm(request.POST, instance=UserForUpdate)
        if form.is_valid():
            user = form.save()
            # active_status = form.cleaned_data.get('active')
            # user.is_active = active_status
            return redirect('/accounts/account_list')
    # else:
    #     form = UsersRegisterForm()
    return render(request, template_name, {'form':form, 'user':UserForUpdate, 'groupName': groupName})



class account_list(TemplateView):
    template_name = 'account_list.html'


@login_required
def get_user_list_for_datatable(request):
    user_list = User.objects.all().select_related()
    data = serializers.serialize('json', user_list)
    return HttpResponse(data, content_type='application/json')

code_base/accounts/templates/account_create.html
{% extends 'home.html' %}
{% block page-title %}
User Registration
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/accounts/account_list">User list</a></li>
    <li class="active">Add User</li>
</ol>
{% endblock %}

{% block right-pane-content %}

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body px-3 py-4">
                        <form method="post" action="" class="row">
                            {% csrf_token %}
                            <!--User name-->
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label" for="{{form.username.id_for_label}}">Username</label>
                                <input id="{{form.username.id_for_label}}" name="{{ form.username.html_name }}"
                                       type="text" class="form-control" aria-required="true"
                                       placeholder="Enter username "
                                       aria-invalid="false">
                                 {% for error in form.username.errors %}
                                <p class="text-danger form-text">{{error}}</p>
                                {% endfor %}
                            </div>

                             <!--User group-->
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">User Group</label><br/>
                                {{form.groups}}
                            </div>


                            <!--Password-->
                            <div class="form-group col-lg-6 col-md-6 col-sm-12 mb-0">
                                <label class="form-control-label">Password</label>
                                <input type="password" class="form-control" placeholder="Password"
                                    name="{{ form.password1.html_name }}" value1="{{ form.password1.value }}">
                                {% for error in form.password1.errors %}
                                <p class="text-danger form-text ">{{error}}</p>
                                {% endfor %}
                            </div>

                            <!--Confirm Password-->
                            <div class="form-group col-lg-6 col-md-6 col-sm-12 mb-0">
                                <label class="form-control-label">Confirm password</label>
                                <input type="password" class="form-control" placeholder="Password"
                               name="{{ form.password2.html_name }}" value1="{{ form.password2.value }}">
                                {% for error in form.password2.errors %}
                                <p class="text-danger form-text">{{error}}</p>
                                {% endfor %}
                            </div>

                            <!--Help text-->
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                 <small class="form-text text-muted pl-4">{{form.password1.help_text }}</small>
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button id="btnSave" type="submit" value="Update" class="btn btn-info">Add</button>
                                <a href="{% url 'account_list' %}"  id="btnCancel" value="cancel" class="ml-2 btn btn-outline-info">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}
{% block page_script %}
<script type="text/javascript">
    jQuery(document).ready(function($) {

        /*set default text for empty option*/
        $('#id_groups').chosen({width: "100%"});
    });
</script>
{% endblock %}

code_base/accounts/templates/account_list.html
{% extends 'home.html' %}
{% block page-title %}
User list
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li class="active">User list</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<!--Right panel - start here -->

<div class="card">
    <div class="card-header bg-info text-white">
        <div class="col-md-10">
            <h5 class="card-title">User List</h5>
        </div>
        <div class="col-md-2">
            <a href="{% url 'account_create' %}" class="pull-right"><button type="button" class="btn btn-light btn-sm"><i class="fa fa-plus"></i></button></a>
        </div>
    </div>
    <div class="card-body">
        <table id="user_list" class="table table-striped table-bordered table-row-clickable" width="100%">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Joining date</th>
                    <th>Last login date</th>
                    <th>Is Active?</th>
                    <th>Group</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

<!-- Right panel - ends here -->
{% endblock %}

{% block page_script %}
<script type="text/javascript">
    var table;

    var showUserStatus = function(data, type, row) {
        if (data == null) return '';
        if (data == true)
            return '<i class="fa fa-check px-3"></i>';
        else
            return '';
    };
    var showUserGroup = function(data, type, row) {
        if (data == null) return '';
        else if (data == 1)
            return 'Admin';
        else if (data == 2)
            return 'Anarde user';
        else if (data ==3)
            return 'Anganwadi worker';
        else if (data ==4)
            return 'Funder';
    };
    /* Init datatable */
    var initDatatable = function($) {
     table = $("#user_list").DataTable({
            "searching": true,
            "processing": true,
            "serverSide": false,
            "1stateSave": true,
            "colReorder": true,
            "paging":true,
            "responsive": true,
            "ajax": {
                 "processing": true,
                 "url": '{% url "get_user_list_for_datatable" %}',
                 "dataSrc": ""
             },
            "columns":[
                {data: 'fields.username'},
                {data: 'fields.date_joined', render: appUtils.formatDatatableDate},
                {data: 'fields.last_login', render: appUtils.formatDatatableDateTime},
                {data: 'fields.is_active', render: showUserStatus},
                {data: 'fields.groups.0', render: showUserGroup},
             ]
        });
    };
    var onUserRowClick = function () {
        var data = table.row( this ).data();
        var url = 'account_update/' + data.pk;
        appUtils.navigateToUrl(url);
    };
     /* init this page */
    var initUserListView = function ($) {
        initDatatable($);
        // bind row click event
        $('#user_list tbody').on('click', 'tr', onUserRowClick);
    };

/* int this page */
    jQuery(document).ready(initUserListView($));

</script>
{% endblock %}

code_base/accounts/templates/account_update.html
{% extends 'home.html' %}
{% block page-title %}
Activate user
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/accounts/account_list">User list</a></li>
    <li class="active">Update User</li>
</ol>
{% endblock %}


{% block right-pane-content %}
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body px-3 py-4">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                                <label class="form-control-label" for="{{form.username.id_for_label}}">Username</label>
                                <input id="{{form.username.id_for_label}}" name="{{ form.username.html_name }}"
                                       value="{{form.username.value}}" type="text" class="form-control"
                                       aria-required="true"
                                       placeholder="Enter username "
                                       aria-invalid="false">
                            </div>
                            <div class="form-group col-lg-4 col-md-4 col-sm-12 ">
                                <label class="form-control-label">User group</label>
                                <input type="text" disabled class="form-control" value="{{groupName}}">
                            </div>
                            <div class="form-group col-lg-4 col-md-4 col-sm-12 ">
                                <label class="form-control-label">Is Active</label><br/>
                                {{form.is_active}}
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button id="btnSave" type="submit" value="Update" class="btn btn-info">Update user</button>
                                <a href="{% url 'account_list' %}"  id="btnCancel" value="cancel" class="ml-2 btn btn-outline-info">Cancel</a>
                            </div>
                            {% for error in form.errors %}
                            <p class="text-danger">please enter valid {{ error }}</p>
                            {% endfor %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %} <!-- end of right-pane-content -->

{% block page_script %}
<script type="text/javascript">
    jQuery(document).ready(function($) {

        /*set default text for empty option*/
        $('#id_is_active').chosen({width: "100%"});
    });

</script>
{% endblock %}

code_base/accounts/templates/user_add_new.html
{% extends 'home.html' %}
{% block page-title %}
User Registration
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/accounts/user_list">User list</a></li>
    <li class="active">Add User</li>
</ol>
{% endblock %}

{% block right-pane-content %}

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body px-3 py-4">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <label class="form-control-label" for="{{form.username.id_for_label}}">Username</label>
                                <input id="{{form.username.id_for_label}}" name="{{ form.username.html_name }}"
                                       type="text" class="form-control" aria-required="true"
                                       placeholder="Enter username "
                                       aria-invalid="false">
                                 {% for error in form.username.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}
                            </div>
                            <div class="form-group col-lg-6 col-md-6 col-sm-12 ">
                                <label class="form-control-label">User Group</label><br/>
                                {{form.groups}}
                            </div>
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <label class="form-control-label">Password</label>
                                <input type="password" class="form-control" placeholder="Password"
                               name="{{ form.password1.html_name }}" value="{{ form.password1.value }}">
                                <small class="form-text text-muted">{{form.password1.help_text }}</small>
                                {% for error in form.password1.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}
                            </div>
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <label class="form-control-label">Confirm
                                    password</label>
                                <input type="password" class="form-control" placeholder="Password"
                               name="{{ form.password2.html_name }}" value="{{ form.password2.value }}">
                                {% for error in form.password2.errors %}
                                <p class="text-danger">{{error}}</p>
                                {% endfor %}
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button id="btnSave" type="submit" value="Update" class="btn btn-info">Save
                                    Information
                                </button>
                                <button id="btnCancel" type="submit" value="cancel" class="ml-2 btn btn-outline-danger">
                                    Cancel
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

code_base/accounts/templates/user_list.html
{% extends 'home.html' %}
{% block page-title %}
User list
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li class="active">User list</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<!--Right panel - start here -->

<div class="card">
    <div class="card-header">
        <div class="col-md-10">
            <strong class="card-title">User list</strong>
        </div>
        <div class="col-md-2" right="align">
            <a href="{% url "user_add" %}"><button type="button" class="btn btn-secondary">Add new user</button></a>
        </div>
    </div>
    <div class="card-body">
        <table id="user_list" class="table table-striped table-bordered" width="100%">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>Date Joined</th>
                    <th>Last Login</th>
                    <th>Active Status</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </div>
</div>

<!-- Right panel - ends here -->
{% endblock %}

{% block page_script %}
<script type="text/javascript">
     var table;
    /* Init datatable */
    var initDatatable = function($) {
     table = $("#user_list").DataTable({
            "searching": true,
            "processing": true,
            "serverSide": false,
            "1stateSave": true,
            "colReorder": true,
            "paging":true,
            "responsive": true,
            "ajax": {
                 "processing": true,
                 "url": '{% url "get_user_list_for_datatable" %}',
                 "dataSrc": ""
             },
            "columns":[
                {data: 'fields.username'},
                {data: 'fields.date_joined'},
                {data: 'fields.last_login'},
                {data: 'fields.is_active'},
             ]
        });
    };
    var onUserRowClick = function () {
        var data = table.row( this ).data();
        var url = 'user_update/' + data.pk;
        navigateToUrl(url);
    };

     /* init this page */
    var initUserListView = function ($) {
        initDatatable($);
        // bind row click event
        $('#user_list tbody').on('click', 'tr', onUserRowClick);
    };

/* int this page */
    jQuery(document).ready(initUserListView($));

</script>
{% endblock %}

code_base/accounts/templates/user_update.html
{% extends 'home.html' %}
{% block page-title %}
Add location
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/accounts/user_list">User list</a></li>
    <li class="active">Update User</li>
</ol>
{% endblock %}


{% block right-pane-content %}
<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body px-3 py-4">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                <label class="form-control-label" for="{{form.username.id_for_label}}">Username</label>
                                <input id="{{form.username.id_for_label}}" name="{{ form.username.html_name }}"
                                       value="{{form.username.value}}" type="text" class="form-control"
                                       aria-required="true"
                                       placeholder="Enter username "
                                       aria-invalid="false">
                            </div>
                            <div class="form-group col-lg-6 col-md-6 col-sm-12 ">
                                <label class="form-control-label">Active status</label><br/>
                                {{form.is_active}}
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button id="btnSave" type="submit" value="Update" class="btn btn-danger">Save
                                    Information
                                </button>
                                <button id="btnCancel" type="submit" value="cancel" class="ml-2 btn btn-outline-danger">
                                    Cancel
                                </button>
                            </div>
                            {% for error in form.errors %}
                            <p class="text-danger">please enter valid {{ error }}</p>
                            {% endfor %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %} <!-- end of right-pane-content -->

{% block page_script %}
<script type="text/javascript">
    jQuery(document).ready(function($) {

        /*set default text for empty option*/
        $('.date-picker select[id $="_month"]').find('option:eq(0)[selected]').html('Select Month');
        $('.date-picker select[id $="_day"]').find('option:eq(0)[selected]').html('Day');
        $('.date-picker select[id $="_year"]').find('option:eq(0)[selected]').html('Year');

        $('#id_date_of_intervention_month').chosen({width: "45%"});
        $('#id_date_of_intervention_day').chosen({width: "25%"});
        $('#id_date_of_intervention_year').chosen({width: "30%"});

        $('#id_exit_date_month').chosen({width: "45%"});
        $('#id_exit_date_day').chosen({width: "25%"});
        $('#id_exit_date_year').chosen({width: "30%"});
    });

</script>
{% endblock %}