code_base/Anarde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home', login_required(TemplateView.as_view(template_name="home.html"))),
    path('location/', include('location.urls')),
    path('survey/', include('survey_form.urls')),
    path('domain/', include('domain.urls')),
    path('funders/', include('funders.urls')),
    path('report/', include('report.urls', namespace='report')),

]

code_base/report/urls.py
from django.urls import path, include
from . import views

app_name = 'report'
urlpatterns = [

    path('survey_pdf/<int:pk>', views.html_to_pdf_generation, name='survey_pdf'),
    path('survey_html_page/<int:pk>', views.survey_html, name='survey_html_page'),
]

code_base/survey_form/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

urlpatterns = [
    #path('json1', views.survey_list1Json.as_view(), name='survey_list_json'),
    path('', views.survey_list1.as_view(), name='survey_list'),
    path('get_survey_list_for_datatable', views.get_survey_list_for_datatable, name='get_survey_list_for_datatable'),
    path('new', views.survey_create, name='survey_new'),
    path('view/<int:pk>', views.survey_view, name='survey_view'),
    path('delete/<int:pk>', views.survey_delete, name='survey_delete'),
    path('edit/<int:pk>', views.survey_update, name='survey_edit'),
    path('survey_suggestion/<int:survey_id>', views.survey_domain_suggestion, name='survey_suggestion'),
    path('survey_program_list/<int:pk>/<int:location_id>', views.survey_program_list, name='survey_program_list'),
    path('show_domainwise_metabase_graph/<int:survey_id>/<int:domain_id>',
         views.show_domainwise_metabase_graph, name='show_domainwise_metabase_graph'),
    path('survey_question_list/<int:pk>/<int:domain_id>', views.survey_question_list, name='survey_question_list'),
    path('survey_location_program_update/<int:pk>/<int:location_id>',
         views.location_program_update, name='survey_location_program_update'),
    path('survey_location_program_update_image_upload/<int:location_id>/<int:domain_program_id>',
         views.location_program_update_image_upload, name='survey_location_program_update_image_upload'),
    path('survey_location_program_update_image_delete/<str:image_name>',
         views.survey_location_program_update_image_delete, name='survey_location_program_update_image_delete'),
    path('get_location_program_list_for_datatable/<int:pk>/<int:location_id>',
         views.get_location_program_list_for_datatable, name='get_location_program_list_for_datatable'),
    path('get_survey_question_list_for_datatable/<int:pk>/<int:domain_id>',
         views.get_survey_question_list_for_datatable, name='get_survey_question_list_for_datatable'),
]

code_base/survey_form/forms.py
import re
import requests

from utils.configuration import kobo_constants, metabase_constants, image_constants
from utils.constants import kobo_form_constants, numeric_constants, code_group_names
from .models import survey

from django.forms import ModelForm
from django import forms
from django.utils.timezone import datetime
from location.models import location, location_program
from common.models import code, code_group

def get_kobo_forms(surveyID=None):
    base_response = requests.get(kobo_constants.kobo_form_link,
                                 headers={'Authorization': kobo_constants.authorization_token}).json()
    list_res = []
    for i in range(len(base_response)):
        surveyObj = survey.objects.filter(kobo_form_id=base_response[i]['formid']).first()
        if surveyObj:
            survey_ID = surveyObj.survey_id
            if survey_ID == surveyID:
                print(base_response[i]['formid'], " ", base_response[i]['title'], " ", base_response[i]['date_created'])
                match = re.search(r'\d{4}-\d{2}-\d{2}', base_response[i]['date_created'])
                date = datetime.strptime(match.group(), '%Y-%m-%d').date()
                res = (base_response[i]['formid'], base_response[i]['title'] + " (" + str(date) + ")")
                list_res.append(res)

        else:
            print(base_response[i]['formid'], " ", base_response[i]['title'], " ", base_response[i]['date_created'])
            match = re.search(r'\d{4}-\d{2}-\d{2}', base_response[i]['date_created'])
            date = datetime.strptime(match.group(), '%Y-%m-%d').date()
            res = (base_response[i]['formid'], base_response[i]['title'] + " (" + str(date) + ")")
            list_res.append(res)

    return sorted(tuple(list_res), reverse=True)


def get_kobo_form_date(kobo_id):
    base_response = requests.get(kobo_constants.kobo_form_link,
                                 headers={'Authorization': kobo_constants.authorization_token}).json()
    publish_date = datetime.now()
    for i in range(len(base_response)):
        if kobo_id == base_response[i]['formid']:
            match = re.search(r'\d{4}-\d{2}-\d{2}', base_response[i]['date_created'])
            publish_date = datetime.strptime(match.group(), '%Y-%m-%d').date()

    return publish_date


class SurveyForm(ModelForm):
    location_queryset = location.objects.all()
    location_id = forms.ModelChoiceField(queryset=location_queryset, empty_label='Select an Option',
                                         label='Location', required=True)

    kobo_forms = get_kobo_forms()
    kobo_form_id = forms.ChoiceField(required=True, label='Select Kobo Form', choices=kobo_forms)

    survey_name = forms.CharField(required=True, label='Survey name', max_length=100)

    code_group_id = code_group.objects.filter(code_group_id=code_group_names.survey_type)
    code_queryset = code.objects.filter(code_group_id=code_group_id[0])
    survey_type_code_id = forms.ModelChoiceField(queryset=code_queryset, empty_label='Select an Option',
                                                 label='Select Survey Type', required=True)

    def __init__(self, *args, **kwargs):
        surveyID = kwargs.pop('surveyID')
        super(SurveyForm, self).__init__(*args, **kwargs)
        self.fields['kobo_form_id'] = forms.ChoiceField(choices=get_kobo_forms(surveyID))

    class Meta:
        model = survey
        fields = ['location_id', 'kobo_form_id', 'survey_name', 'survey_type_code_id']


# location program list form
class LocationProgram_Form(ModelForm):
    YEARS = [x for x in range(1990, 2021)]

    date_of_implementation = forms.DateField(required=True,
                                           label='Date of implementation',
                                           widget=forms.SelectDateWidget(empty_label="", years=YEARS))

    before_image_upload = forms.ImageField(required=False, widget=forms.widgets.ClearableFileInput())
    after_image_upload = forms.ImageField(required=False, widget=forms.widgets.ClearableFileInput())
    notes = forms.CharField(required=True, label='notes')
    class Meta:
        model = location_program
        fields = ['date_of_implementation', 'before_image_upload', 'after_image_upload', 'notes']

code_base/survey_form/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from django.core import serializers
from itertools import chain

from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.generic import TemplateView

import json
import jwt

from utils.configuration import kobo_constants, metabase_constants, image_constants, aws_bucket_constants
from utils.constants import kobo_form_constants, numeric_constants, code_group_names

from common.models import code, code_group
from location.models import location, location_program, location_program_image
from domain.models import domain, domain_program
from .models import survey, survey_question
from .forms import get_kobo_form_date, SurveyForm, LocationProgram_Form
from survey_response.models import survey_response, survey_response_detail
from survey_response import views as response_views


class survey_list1(TemplateView):
    template_name = 'survey_list.html'


class survey_list1Json(BaseDatatableView):
    model = survey
    columns = ['survey_id','survey_name', 'survey_type_code_id.code_name', 'publish_date', 'created_by', 'location_id.location_name']
    order_columns = ['survey_name', 'survey_type_code_id.code_name', 'publish_date', 'created_by', 'location_id.location_name']


@login_required
def get_survey_list_for_datatable(request):
    survey_list = survey.objects.all()
    data = serializers.serialize('json', survey_list, use_natural_foreign_keys=True)
    return HttpResponse(data, content_type='application/json')


@login_required
def survey_create(request, template_name='survey_create.html'):
    if request.method == 'POST':
        form = SurveyForm(request.POST, surveyID=None)
        print(form.data)
        if form.is_valid():
            publish_date = get_kobo_form_date(int(form.cleaned_data['kobo_form_id']))
            info = form.save(commit=False)
            info.publish_date = publish_date
            info.created_by = request.user
            info.modified_by = request.user
            info.save()
            return redirect('/survey/')
        else:
            print(form.errors)
    else:

        form = SurveyForm(initial={'kobo_form_id': 'Select an Option'},surveyID=None)

    return render(request, template_name, {'form':form})


@login_required
def survey_delete(request, pk, template_name='survey_delete.html'):
    surveys = get_object_or_404(survey, pk=pk)
    if request.method == 'POST':
        surveys.delete()
        return redirect('/survey/')

    return render(request, template_name, {'object': surveys})


@login_required
def survey_update(request, pk, template_name='survey_update.html'):
    surveyForUpdate = get_object_or_404(survey, pk=pk)
    form = SurveyForm(instance=surveyForUpdate, surveyID=pk)
    if request.method == 'POST':
        print(request.POST)
        if 'cancel' in request.POST:
            print('cancelling request')
            return redirect('/survey/view/'+ str(pk))

        form = SurveyForm(request.POST, instance=surveyForUpdate, surveyID=pk)
        if form.is_valid():
            info = form.save()
            info.modified_by = request.user
            info.save()
            return redirect('/survey/view/'+ str(pk))
        else:
            print(form.errors)
    # else:
    #     form = LocationForm
    form.pk = pk
    return render(request, template_name, {'form':form, 'survey':surveyForUpdate})


@login_required
def get_kobo_form(request,pk):
    survey_id = get_object_or_404(survey, pk=pk)
    print(survey_id)
    return render(request, {'survey': survey_id})


@login_required
def survey_view(request, pk, template_name='survey_detail.html'):
    objsurvey = get_object_or_404(survey, pk=pk)
    error_log = []
    # Pull kobo form data
    if request.method == 'POST':
        # print(request.POST)

        if 'pull-form-data' in request.POST:
            # print("kobo form data")
            error_log = response_views.pull_kobo_form_data(objsurvey)

        elif 'pull-response-data' in request.POST:
            response_views.pull_kobo_response_data(objsurvey)

    print(error_log)
    # Show / Hide delete button
    show_delete_survey_button = True
    survey_response_exists = survey_response.objects.filter(survey_id=objsurvey).first()
    if survey_response_exists:
        survey_response_detail_exists = survey_response_detail.objects.filter(survey_response_id=survey_response_exists).first()

        if survey_response_detail_exists:
            show_delete_survey_button = False

    return render(request, template_name, {'object': objsurvey, 'show_delete': show_delete_survey_button,
                                           'error_log':error_log , 'iframeUrl': '', 'domain_id':1})


def get_iframeURL(objDomain, survey_id):
    # Payload for metabase graphs
    payload = {
        "resource": {"dashboard": objDomain.metabase_dashboard_id},
        "params": {
            "survey_id": survey_id
        }
    }

    # Build iframe url
    token = jwt.encode(payload, metabase_constants.metabase_secret_key, algorithm="HS256")
    iframeUrl = metabase_constants.metabase_site_url + "/embed/dashboard/" + token.decode(
        "utf8") + "#bordered=false&titled=false"

    return iframeUrl


def show_domainwise_metabase_graph(request, survey_id, domain_id):
    # Get domain object
    # objDomain = get_object_or_404(domain, pk=domain_id)
    try:
        objDomain = domain.objects.get(pk = domain_id)
    except domain.DoesNotExist:
        objDomain = None

    if objDomain == None or objDomain.metabase_dashboard_id == None:
        responseData = {}
        responseData['iframeUrl'] = ''
    else:
        iframeUrl = get_iframeURL(objDomain, survey_id)
        responseData = {}
        responseData['iframeUrl'] = iframeUrl

    data = json.dumps(responseData) #{'iframeUrl': iframeUrl}
    return HttpResponse(data, content_type='application/json')


def survey_domain_suggestion(request, survey_id):
    """
    Returns a list of domains based on survey
    :param request:
    :param survey_id: The survey id, whose domains are to be found out
    :return:
    """
    # Get list of distinct domain ids, applicable for the current survey
    distinct_domain_ids = survey_question.objects.values('domain_id').filter(survey_id = survey_id).distinct()

    # Get list of domain objects based on distinct domain list above
    domain_list = domain.objects.filter(domain_id__in=[item['domain_id'] for item in distinct_domain_ids])

    obj_survey = survey.objects.get(survey_id = survey_id)
    obj_location = location.objects.get(location_id = obj_survey.location_id.location_id)
    data_json = serializers.serialize('json', domain_list)
    data_list = json.loads(data_json)
    for item in data_list:
        index_value = response_views.get_domain_index(item['fields']['kobo_group_key'], survey_id)
        item.update({"index": index_value})
        item.update({"location_id": obj_location.location_id}) # location id of conducted survey

    data = json.dumps(data_list)

    return HttpResponse(data, content_type='application/json')


@login_required
def survey_program_list(request, pk, location_id, template_name='survey_program_list.html'):
    obj_domain = domain.objects.get(domain_id=pk)
    obj_location = location.objects.get(location_id= location_id)
    return render(request, template_name, {'obj_domain': obj_domain , 'obj_location':obj_location})


@login_required
def get_location_program_list_for_datatable(request, pk, location_id):
    program_list = domain_program.objects.filter(domain_id=pk).values('domain_program_id','program_name','description')
    for item in program_list:
        program_id = item['domain_program_id']
        if location_program.objects.filter(program_id=program_id, location_id=location_id ).exists():
            obj_location_program = location_program.objects.filter(program_id=program_id, location_id=location_id ).\
                values('location_program_id', 'date_of_implementation','notes','location_id_id')
            for i in obj_location_program:
                item.update(i)
        else:
            i = {'date_of_implementation': None, 'notes': None , 'location_id_id': location_id}
            item.update(i)
    data1 = list(program_list)
    data = json.dumps(data1, indent=4, sort_keys=True, default=str)
    return HttpResponse(data, content_type='application/json')


@login_required
@csrf_exempt
def location_program_update_image_upload(request, location_id, domain_program_id):
    obj_program = domain_program.objects.get(pk=domain_program_id)
    print(obj_program)

    if location_program.objects.filter(location_id=location_id, program_id=obj_program).exists():
        objlocation = location_program.objects.get(location_id=location_id, program_id=obj_program)

        print(objlocation)
        print("in upload image")
        if request.is_ajax():
            print(request.FILES)
            location_names = []
            image_names = []
            image_list = []
            for filename, file in request.FILES.items():
                single_image = request.FILES[filename]
                print(single_image)

                if 'before' in filename.lower():
                    location1, image_name = response_views.save_images(single_image, image_constants.image_type_before)

                    image_type = code.objects.filter(code_id=numeric_constants.before_images).first()
                    print(image_type)
                else:
                    location1, image_name = response_views.save_images(single_image, image_constants.image_type_after)
                    image_type = code.objects.filter(code_id=numeric_constants.after_images).first()

code_base/survey_form/templates/survey_delete.html
{% extends 'home.html' %}
{% block page-title %}
Delete Survey
{% endblock %}
 {% block page-title-path %}
<ol class="breadcrumb text-right">
                            <li><a href="/location">Survey</a></li>
                            <li><a href="/location">Details</a></li>
                            <li class="active">Delete</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<div class="card">
    <div class="card-header">
        <strong class="card-title">Survey Delete</strong>
    </div>
    <div class="card-body">

        <form method="post">{% csrf_token %}
            Are you sure you want to delete {{object.survey_name}} ?
            <input type="submit" value="submit"  class="btn btn-danger "/>
        </form>
    </div>
</div>


{% endblock %}

code_base/survey_form/templates/survey_detail.html
{% extends 'home.html' %}
{% block page-title %}
Survey Details
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/survey">Surveys</a></li>
    <li class="active">Details</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<div class="card">
    <form method="post" action="">
        {% csrf_token %}
        <!--Survey details - -->
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12" >
                        <h3 class="card-title">{{object.survey_name}}
                            <a href='{% url "survey_edit" object.survey_id %}' class="text-info" title="Edit survey details">
                                <i class="fa fa-pencil-square-o px-3"></i>
                            </a>
                        </h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <dl>
                            <dt>Survey Type</dt>
                            <dd>{{ object.survey_type_code_id.code_name }}</dd>
                        </dl>
                    </div>
                    <div class="col-3">
                        <dl>
                            <dt>Publish date</dt>
                            <dd>{{ object.publish_date }}</dd>
                        </dl>
                    </div>
                    <div class="col-3" id="divSurveyLocation" location-id="{{ object.location_id.location_id }}">
                        <dl>
                            <dt>Location</dt>
                            <dd>{{ object.location_id.location_name }}</dd>
                        </dl>
                    </div>
                    <div class="col-3">
                        <dl>
                            <dt>Survey Created by</dt>
                            <dd>{{ object.created_by }}</dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>

        <!--Buttons in footer of survey details -->
        <div class="card-footer bg-light">
            <!--<div class="container">-->
            <div class="row">
                <div class="col-md-2">
                    <button id="pull-form-data" type="submit" name="pull-form-data" value="pull_kobo_form_data"
                            class="btn btn-md btn-info">
                        Pull Kobo Questions
                    </button>
                </div>

                <div class="col-md-4">
                    <button id="pull-response-data" type="submit" name="pull-response-data" value="pull_kobo_data" class="btn btn-md btn-info">
                        Pull Kobo Data
                    </button>
                </div>
                <div class="col-md-3">
                    <a href = "{% url 'survey_question_list' object.survey_id domain_id %}" >
                        <button type = "button" class ="ml-2 btn btn-outline-info d-none" > Survey Questions </button >
                    </a>
                </div>
                <div class="col-md-3">
                    <a href = "{% url 'report:survey_pdf' object.survey_id %}" target="_blank" >
                        <button type = "button" class ="ml-2 btn btn-outline-info" >Survey report</button >
                    </a>
                </div>


                <!--{{ show_delete }}-->
                {% if show_delete %}

                <div class="col-md-3">
                    <a href='{% url "survey_delete" object.survey_id %}' class="btn btn-danger">Delete survey</a>
                </div>
                {% endif %}

            </div>
            <!-- </div>-->
        </div>
    </form>
</div>
<!--Display survey graphs -->
<div class="card d-none">
    <div class="card-header bg-info text-white">
        <h5> Data of {{object.survey_name}}</h5>
    </div>
    <div class="card-body">
    </div>
</div>

<div class="card">
    <div class="card-header bg-info text-white d-none">
        <h5> Survey analysis</h5>
    </div>
    <div class="card-body">
        <div class="custom-tab">

            <div>
                <ul class="nav nav-tabs" id="nav-tab" role="tablist">
                    <li class="nav-item" id="tab-domain-index">
                        <a class="nav-link active show" data-toggle="tab"
                           href="#tab-domain-index-content" role="tab" aria-controls="tab-domain-index-content" aria-selected="true">Domainwise index</a>
                    </li>
                    <li class="nav-item" id="tab-analysis">
                        <a class="nav-link" data-toggle="tab"
                           href="#tab-analysis-content" role="tab" aria-controls="tab-analysis-content" aria-selected="false">Analysis</a>
                    </li>
                    <li class="nav-item" id="tab-suggestions">
                        <a class="nav-link" data-toggle="tab"
                           href="#tab-suggestions-content" role="tab" aria-controls="tab-suggestions-content" aria-selected="false">Suggestions
                        </a>
                    </li>
                    <li class="nav-item" id="tab-questions">
                        <a class="nav-link" data-toggle="tab"
                           href="#tab-questions-content" role="tab" aria-controls="tab-questions-content" aria-selected="false">Questions
                        </a>
                    </li>
                </ul>
            </div>
            {% if error_log %}
            <div class="pl-2">Following errors encountered</div>
            <ul class="pl-4">
                {% for error in error_log %}
                <li>
                    <small> {{ error }}</small>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            <div class="tab-content pl-3 py-5" id="nav-tabContent">
                <!--Content for domainwise index tab -->
                <div class="tab-pane fade active show" id="tab-domain-index-content" role="tabpanel" aria-labelledby="tab-domain-index-content">
                    <h3 class="px-3 mb-3">Vulnerability index</h3>
                    <div id="domain-list">
                        <center><img src="/static/images/spinner.gif" class="py-5"></center>
                    </div>
                </div>

                <!--Content for analysis tabs -->
                <div class="tab-pane fade" id="tab-analysis-content" role="tabpanel" aria-labelledby="custom-nav-profile-tab">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <h3 class="px-3 mb-3 selectedDomainName" prefixtext="Graphical analysis for "></h3>
                                <iframe id="frmGraphs" src=""  width="100%" height="900" frameborder="0"></iframe>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Content  for suggestions -->
                <div class="tab-pane fade" id="tab-suggestions-content" role="tabpanel" aria-labelledby="tab-suggestions-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <h3 class="px-3 mb-3 selectedDomainName" prefixtext="Program suggestions for "></h3>
                                <div class="iframe-container">
                                    <iframe id="frmSuggestion" src=""  width="100%" frameborder="0"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Content for survey questions -->
                <div class="tab-pane fade" id="tab-questions-content" role="tabpanel" aria-labelledby="tab-questions-content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 col-md-12">
                                <h3 class="px-3 mb-3 selectedDomainName" prefixtext="Survey questions for "></h3>
                                <div class="iframe-container">
                                    <iframe id="frmQuestion" src=""  width="100%" frameborder="0"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

{% endblock %}


{% block page_script %}
<script type="text/javascript">

var showDomain = function ($) {
    var showDomainSuccessCB = function (response) {
        console.log('In success');
        console.log(response);
        var allDomainHtml = '';
        var replacedHtml = '';
        var domainCardTemplate = '<div id ="domain_box" class="col-sm-6 col-lg-3 card-clickable">' +
                        '<div  class="card text-white [color-code] domain-index" domain-id=[domain_id] >' +
                            '<div class="card-body pb-0">' +
                                '<p class="text-light">[domain_name]</p>' +
                                '<div class="chart-wrapper px-0 card-domain-index stat-widget-one">' +
                                     '<strong class="count stat-digit text-white">[vulnerability_index] %</strong>' +
                                '</div>' +
                            '</div>' +
                        '</div>' +
                    '</div>'


        for (index = 0; index < response.length; index++) {
            //bg-flat-color-2
            replacedHtml = domainCardTemplate.replace('[domain_name]', response[index].fields.domain_name);
            replacedHtml = replacedHtml.replace('[domain_id]', response[index].pk);
            replacedHtml = replacedHtml.replace('[vulnerability_index]', response[index].index );

            vulnerability_index = response[index].index;
            color_code = 'bg-flat-color-2'
            if( vulnerability_index < 25) {
                color_code = 'bg-danger';
            } else if( vulnerability_index >= 25 && vulnerability_index < 50) {
                color_code = 'bg-danger-light';
            } else if( vulnerability_index >= 50 && vulnerability_index < 75) {
                color_code = 'bg-flat-color-2';
            } else {
                color_code = 'bg-success';
            }

            replacedHtml = replacedHtml.replace('[color-code]', color_code );
            //var domain_id = response[index].pk
            //var location_id = response[index].location_id
            //replacedHtml = replacedHtml.replace('[next_page]', 'href="/survey/survey_program_list/'+ domain_id+'/'+location_id+'"');
            allDomainHtml += replacedHtml;
        }
        $('#domain-list').html(allDomainHtml);
    };

    var showDomainErrorCB = function (response) {
        console.log('In error');
        console.log(response);
    };

    $.ajax({
        url: '{% url "survey_suggestion" object.survey_id %}',
        success: showDomainSuccessCB,
        error: showDomainErrorCB
    });
};


var setQuestionContent = function (domain_id) {
    $('iframe#frmQuestion').attr('src', '/survey/survey_question_list/{{object.survey_id }}/' + domain_id)
}

var setProgramSuggestionContent = function (domain_id) {
    location_id = $('#divSurveyLocation').attr('location-id');
    $('iframe#frmSuggestion').attr('src', '/survey/survey_program_list/' + domain_id + '/' + location_id)
}

var showDomainWiseGraph = function (domain_id) {
    var showDomainWiseGraphSuccessCB = function (response) {
        if (response.iframeUrl == '') {

        }
        $('iframe#frmGraphs').attr('src', response.iframeUrl);
    };

    var showDomainWiseGraphErrorCB = function (response) {
        console.log('There was some error when fetching graphs');
        console.log(response);
    };

    var showDomainWiseGraphCompleteCB = function () {
        $('iframe#frmGraphs').removeClass('spinner');
    }

    $('iframe#frmGraphs').addClass('spinner');
    var ajaxUrl = '/survey/show_domainwise_metabase_graph/{{object.survey_id }}/' + domain_id;
    $.ajax({
        url: ajaxUrl,
        success: showDomainWiseGraphSuccessCB,
        error: showDomainWiseGraphErrorCB,
        complete: showDomainWiseGraphCompleteCB
    });
};

var activateTab = function (tabSelector) {
    $('.nav.nav-tabs .nav-item a.active.show').removeClass('active show');
    $('.nav.nav-tabs .nav-item' + tabSelector + ' a').addClass('active show');

    tabContentID = $('.nav.nav-tabs .nav-item' + tabSelector + ' a').attr('aria-controls');
    $('.tab-content .tab-pane.active.show').removeClass('active show');
    $('#' + tabContentID).addClass('active show');
};

var domainCardOnClick = function (e) {
    domain_card = $(e.currentTarget).find('.card');
    domain_id = domain_card.attr('domain-id');
    domain_name = domain_card.find('p').html();

    //heading = $('.selectedDomainName').attr('prefixtext')

    $('.selectedDomainName').html( domain_name)
    activateTab('#tab-analysis');

    showDomainWiseGraph(domain_id);
    setProgramSuggestionContent(domain_id);
    setQuestionContent(domain_id);
};

var initSurveyDetailView = function (dollar) {
   $ = dollar;

  // register on click event
  showDomain($);
  var domainCard = $('#tab-domain-index-content');
  domainCard.on('click', '.card-clickable', domainCardOnClick);
};
var $;
jQuery(document).ready(initSurveyDetailView($));

</script>
{% endblock %}