code_base/Anarde/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home', login_required(TemplateView.as_view(template_name="home.html"))),
    path('location/', include('location.urls')),
    path('survey/', include('survey_form.urls')),
    path('domain/', include('domain.urls')),
    path('funders/', include('funders.urls')),
    path('report/', include('report.urls', namespace='report')),

]

code_base/funders/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.funder_list.as_view(), name='funder_list'),
    path('funder_create/',views.funder_create, name='funder_create'),
    path('view/<int:pk>', views.funder_view, name='funder_view'),
    path('edit/<int:pk>', views.funder_update, name='funder_edit'),
    path('delete/<int:pk>', views.funder_delete, name='funder_delete'),
    path('funder_list', views.funder_list.as_view(), name='funder_list'),
    path('get_funder_list_for_datatable',views.get_funder_list_for_datatable, name='get_funder_list_for_datatable'),

    path('program_list/<int:pk>', views.get_funder_program_list_for_datatable, name='get_funder_program_list_for_datatable'),
    path('add_program/<int:id>', views.add_program, name='add_program'),
    path('view_program/<int:pk>', views.view_program, name='view_program'),
    path('update_program/<int:pk>', views.update_program, name='update_program'),

    path('load_location_programs/<int:pk>', views.load_location_programs, name='load_location_programs'),
]

code_base/funders/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth.models import User
from location.models import location_program

class funder(models.Model):
    funder_id = models.BigAutoField(primary_key=True)
    user_id = models.ForeignKey(User, null=False, db_column='user_id', related_name='fk_funder_uid',
                                   on_delete=models.PROTECT)

    organization_name = models.CharField(max_length=255, null=False)

    funding_amount = models.IntegerField(null=True, blank=True)
    funding_date = models.DateField(null=False)

    created_by = models.ForeignKey(User, null=True, db_column='created_by', related_name='fk_funder_cby',
                                   on_delete=models.PROTECT)
    created_on = models.DateTimeField(default=datetime.now)

    modified_by = models.ForeignKey(User, null=True, db_column='modified_by', related_name='fk_funder_mby',
                                    on_delete=models.PROTECT)
    modified_on = models.DateTimeField(default=datetime.now)

    class Meta:
        db_table = 'fun_funder'
        get_latest_by = 'funder_id'


class funder_program(models.Model):
    funder_program_id = models.BigAutoField(primary_key=True)

    funder_id = models.ForeignKey('funder', null=False, blank=False, db_column='funder_id',
                                    related_name='fk_funder_id', on_delete=models.PROTECT)

    location_program_id = models.ForeignKey(location_program, null=False, db_column='location_program_id',
                                            related_name='fk_loc_program_id', on_delete=models.PROTECT)

    funding_amount = models.IntegerField(null=False, blank=False)

    class Meta:
        db_table = 'fun_funder_program'
        get_latest_by = 'funder_program_id'

code_base/funders/forms.py
from django.forms import ModelForm
from django import forms
from django.shortcuts import  get_object_or_404
from django.contrib.auth.models import User
from utils.constants import code_group_names
from .models import funder, funder_program
from location.models import location, location_program


class FunderForm(ModelForm):

    user_queryset = User.objects.filter(groups__name=code_group_names.funder)
    user_id = forms.ModelChoiceField(queryset=user_queryset, empty_label='Select an Option',
                                     label='User', required=True)

    YEARS = [x for x in range(1990, 2021)]
    funding_date = forms.DateField(required=False, label='Date of Funding',
                                      widget=forms.SelectDateWidget(empty_label="", years=YEARS))

    class Meta:
        model = funder
        fields = ['user_id', 'organization_name', 'funding_amount', 'funding_date']


class FunderProgramForm(ModelForm):

    location_queryset = location.objects.all()
    location_id = forms.ModelChoiceField(queryset=location_queryset, empty_label='Select an Option',
                                         label='Location', required=True)

    program_queryset = location_program.objects.all()
    location_program_id =forms.ModelChoiceField(queryset=program_queryset, empty_label='Select an Option',
                                          label='Program', required=True)

    def __init__(self, *args, **kwargs):
        funder_ID = kwargs.pop('funderID')
        super(FunderProgramForm, self).__init__(*args, **kwargs)

        funded_amt = get_object_or_404(funder, funder_id=funder_ID).funding_amount
        print(funded_amt)

        programs_funded = funder_program.objects.filter(funder_id=funder_ID)
        if programs_funded:
            for program in programs_funded:
                amount = program.funding_amount
                funded_amt -= amount

        print(funded_amt)
        self.fields['funding_amount'] = forms.IntegerField(min_value=1, max_value=funded_amt)
        #self.fields['location_program_id'].queryset = location_program.objects.none()
        #print(self.data)
        if 'location' in self.data:
            print("****")
            try:
                location_id = int(self.data.get('location'))
                queryset = location_program.objects.filter(location_id=location_id)#.order_by('name')
                self.fields['location_program_id'].queryset = queryset
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        # elif self.instance.pk:
        #     self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

    class Meta:
        model = funder_program
        fields = ['location_program_id', 'funding_amount', 'location_id']

code_base/funders/views.py
from django.shortcuts import render
from django.views.generic import UpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login

from django.contrib.auth.decorators import login_required
from django_datatables_view.base_datatable_view import BaseDatatableView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.core import serializers
from .forms import FunderForm, FunderProgramForm
from .models import funder, funder_program
from location.models import location, location_program
from django.views.decorators.csrf import csrf_exempt
import json


class funder_list(TemplateView):
    template_name = 'funder_list.html'


@login_required
def get_funder_list_for_datatable(request):
    funder_list = funder.objects.all()
    data = serializers.serialize('json', funder_list)
    return HttpResponse(data, content_type='application/json')



@login_required
def funder_create(request, template_name='funder_create.html'):
    if request.method == 'POST':
        form = FunderForm(request.POST)
        print(form.data)
        if form.is_valid():
            info = form.save(commit=False)
            info.created_by = request.user
            info.modified_by = request.user
            info.save()
            return redirect('/funders/')
        else:
            print(form.errors)
    else:

        form = FunderForm

    return render(request, template_name, {'form':form})


@login_required
def funder_view(request, pk, template_name='funder_detail.html'):
    funders= get_object_or_404(funder, pk=pk)
    return render(request, template_name, {'object':funders})


@login_required
def funder_update(request, pk, template_name='funder_update.html'):
    funderForUpdate = get_object_or_404(funder, pk=pk)
    form = FunderForm(instance=funderForUpdate)
    if request.method == 'POST':
        form = FunderForm(request.POST, instance=funderForUpdate)
        if form.is_valid():
            info = form.save()
            info.modified_by = request.user
            info.save()
            return redirect('/funders/view/'+ str(pk))
        else:
            print(form.errors)
    # else:
    #     form = LocationForm
    form.pk = pk
    return render(request, template_name, {'form':form, 'location':funderForUpdate})


@login_required
def funder_delete(request, pk, template_name='funder_delete.html'):
    funders = get_object_or_404(funder, pk=pk)
    if request.method == 'POST':
        funders.delete()
        return redirect('/funders/')

    return render(request, template_name, {'object': funders})


@login_required
def get_funder_program_list_for_datatable(request, pk):
    program_list = funder_program.objects.filter(funder_id=pk)
    data = serializers.serialize('json', program_list, use_natural_foreign_keys=True)
    return HttpResponse(data, content_type='application/json')

@login_required
def view_program(request, pk, template_name='funder_program_detail.html'):
    obj_program = get_object_or_404(funder_program, pk=pk)
    return render(request, template_name, {'object':obj_program})


@login_required
@csrf_exempt
def load_location_programs(request, pk):
    print(request)
    location_id = get_object_or_404(location, pk=pk)
    programs = location_program.objects.filter(location_id=location_id) #.order_by('name')
    print(programs)
    # for program in programs:
    #     program_list
    programs_json = serializers.serialize('json', programs)
    print(programs_json)

    # data_list = json.loads(programs_json)
    # for item in data_list:
    #     item.update({"index": index_value})
    #     item.update({"location_id": obj_location.location_id})  # location id of conducted survey
    #
    # data = json.dumps(data_list)
    # data = json.dumps(programs)
    return HttpResponse(programs_json, content_type='application/json')
    #return render(request, {'programs': programs})


@login_required
def add_program(request, id, template_name='add_funder_program.html'):
    obj_funder = get_object_or_404(funder, funder_id=id)
    print(obj_funder)
    if request.method == 'POST':
        form = FunderProgramForm(request.POST, funderID=id)
        if form.is_valid():
            info = form.save(commit=False)
            info.funder_id = obj_funder
            info.save()
            return redirect('/funders/view/'+ str(id))
        else:
            print(form.errors)
    else:
        form = FunderProgramForm(funderID=id)

    return render(request, template_name, {'form': form, 'object': obj_funder})

@login_required
def update_program(request, pk, template_name='update_funder_program.html'):
    programForUpdate = get_object_or_404(funder_program, pk=pk)
    obj_funder = funder.objects.get(funder_id = programForUpdate.funder_id.funder_id)
    form = FunderProgramForm(instance=programForUpdate)
    if request.method == 'POST':
        if 'cancel' in request.POST:
            print('cancelling request')
            return redirect('/funder/view_program/'+ str(pk))
        form = FunderProgramForm(request.POST, instance=programForUpdate)
        if form.is_valid():
            info = form.save()
            info.modified_by = request.user
            info.save()
            return redirect('/funders/view_program/'+ str(pk))
        else:
            print(form.errors)
    return render(request, template_name, {'form':form, 'obj_funder':obj_funder})

code_base/funders/templates/add_funder_program.html
{% extends 'home.html' %}

{% block page-title %}
  Add Funder Program
{% endblock %} <!-- end of block page-title -->

{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/funders/">Funders</a></li>
    <li class="active">Add program</li>
</ol>
{% endblock %} <!-- end of block page-title-path -->
{% block right-pane-content %}
<div class="content mt-3">
    <div class="animated fadeIn">

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body  px-3 py-4">
                        <form  method="post" action="" class="row">
                            {% csrf_token %}
                            <div class="form-group col-lg-6 col-md-6 col-sm-12 ">
                                <label class="form-control-label">Organization</label>
                                <input type="text" disabled class="form-control" value="{{object.organization_name}}">
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">Select Location</label>
                                {{form.location_id}}
                                {% for error in form.location_id.errors %}
                                <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">Select Program</label>
                                {{form.location_program_id}}
                                <small class="form-text text-danger">{{form.location_program_id.errors}}</small>
                                {% for error in form.location_program_id.errors %}
                                    <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">Funding Amount</label>
                                <input id="{{form.funding_amount.id_for_labe}}" name="{{ form.funding_amount.html_name }}"
                                       type="text" class="form-control" data-val="true" placeholder="Enter funding amount"
                                       aria-required="true" aria-invalid="false" required/>

                                {% for error in form.funding_amount.errors %}
                                <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>

                            <!--{% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <small class="form-text text-danger">{{error| escape}}</small>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}-->
                            <div>
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button id=btnSave" type="submit" value="add" class="btn btn-info">Add</button>
                                    <a href="{% url 'funder_view' object.funder_id %}" id="btnCancel"  class="ml-2 btn btn-outline-info">Cancel</a>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} <!-- end of right-pane-content -->

{% block page_script %}
<script type="text/javascript">


    function populatePrograms(location_id){
        console.log(location_id);
        var populateProgramsSuccessCB = function (response) {
            console.log(response);
            console.log(response.length);

            for(var i=0;i < response.length;i++){
                console.log(response[i]);
                console.log(response[i]['fields']['program_id'])
                $('#id_location_program_id').append($('<option>', {
                    value: response[i]['fields']['program_id'],
                    text: response[i]['fields']['program_id']
            }));
            }
            /*$("#id_location_program_id").html(response);*/
        };

        var populateProgramsErrorCB = function (response) {
            console.log('In error');
            console.log(response);
        };

        ajaxURL = '/funders/load_location_programs/'+location_id;
        console.log(ajaxURL);

        $.ajax({
            /*type: "POST",*/
            url: ajaxURL,
            processData: false,
            contentType: false,
            success: populateProgramsSuccessCB,
            error: populateProgramsErrorCB
        });
    };


    jQuery(document).ready(function($) {
        $('#id_date_of_implementation_month').chosen({width: "30%"});
        $('#id_date_of_implementation_day').chosen({width: "16%"});
        $('#id_date_of_implementation_year').chosen({width: "20%"});
        $('select').chosen({width:'100%'});

        $("#id_location_id").change(function () {
            var location_id = $(this).val();
            //console.log(location_id);
            //populatePrograms(location_id);
        });
    });
  </script>

{% endblock %}

code_base/funders/templates/funder_create.html
{% extends 'home.html' %}

{% block page-title %}
  Add Funder
{% endblock %} <!-- end of block page-title -->

{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/funders/">Funders</a></li>
    <li class="active">Add funder</li>
</ol>
{% endblock %} <!-- end of block page-title-path -->



{% block right-pane-content %}
<div class="content mt-3">
    <div class="animated fadeIn">

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body px-3 py-4">
                        <form  method="post" action="" class="row">
                            {% csrf_token %}
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">Organization name</label>
                                <input id="{{form.organization_name.id_for_label}}" name="{{ form.organization_name.html_name }}"
                                       type="text" class="form-control" data-val="true" placeholder="Enter organization name"
                                       aria-required="true" aria-invalid="false" required>
                                {% for error in form.organization_name.errors %}
                                    <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label">Reporting Contact</label>
                                {{form.user_id}}
                                {% for error in form.user_id.errors %}
                                <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>

                            <div class="form-group col-lg-6 col-md-6 col-sm-12 date-picker">
                                <label class="form-control-label">Date of Funding</label><br/>
                                {{form.funding_date}}
                                {% for error in form.funding_date.errors %}
                                    <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>

                            <!--funding amt -->
                            <div class="form-group col-lg-6 col-md-6 col-sm-12">
                                <label class="form-control-label"> Funding Amount(in INR) </label>
                                <input id="{{form.funding_amount.id_for_label}}" name="{{ form.funding_amount.html_name }}"
                                       type="text" class="form-control" data-val="true" placeholder="Enter amount"
                                       aria-required="true" aria-invalid="false" required>
                                {% for error in form.funding_amount.errors %}
                                <small class="form-text text-danger">{{error}}</small>
                                {% endfor %}
                            </div>

                            <div>
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <button id=btnSave" type="submit" value="add" class="btn btn-info">Add</button>
                                    <a href="{% url 'funder_list' %}" id="btnCancel"  class="ml-2 btn btn-outline-info">Cancel</a>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %} <!-- end of right-pane-content -->

{% block page_script %}
<script type="text/javascript">
    jQuery(document).ready(function($) {

        $('.date-picker select[id $="_month"]').find('option:eq(0)[selected]').html('Select Month');
        $('.date-picker select[id $="_day"]').find('option:eq(0)[selected]').html('Day');
        $('.date-picker select[id $="_year"]').find('option:eq(0)[selected]').html('Year');
        $('#id_funding_date_month').chosen({width: "30%"});
        $('#id_funding_date_day').chosen({width: "20%"});
        $('#id_funding_date_year').chosen({width: "20%"});
        $('select').chosen({width:'100%'});
    });
</script>
{% endblock %}

code_base/funders/templates/funder_delete.html
{% extends 'home.html' %}
{% block page-title %}
Funder Details
{% endblock %}
 {% block page-title-path %}
<ol class="breadcrumb text-right">
                            <li><a href="/funders">Funders</a></li>
                            <li><a href="/funders">Details</a></li>
                            <li class="active">Delete</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<div class="card">
    <div class="card-header">
        <strong class="card-title">Funder Delete</strong>
    </div>
    <div class="card-body">

        <form method="post">{% csrf_token %}
            Are you sure you want to delete "{{ object.organization_name}}" ?
            <input type="submit" value="submit"  class="btn btn-danger "/>
        </form>
    </div>
</div>


{% endblock %}

code_base/funders/templates/funder_detail.html
{% extends 'home.html' %}
{% block page-title %}
Funder details
{% endblock %}
{% block page-title-path %}
<ol class="breadcrumb text-right">
    <li><a href="/funders">Funders</a></li>
    <li class="active">Details</li>
</ol>
{% endblock %}
{% block right-pane-content %}
<div class="card">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12" >
                    <h3 class="card-title">{{object.organization_name}}
                        <a href='{% url "funder_edit" object.funder_id %}' class="text-info" title="Edit funder details">
                            <i class="fa fa-pencil-square-o px-3"></i>
                        </a>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <dl>
                        <dt>Username</dt>
                        <dd>{{ object.user_id }}</dd>
                    </dl>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <dl>
                        <dt>Date of intervention</dt>
                        <dd>{{ object.funding_date }}</dd>
                    </dl>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-12">
                    <dl>
                        <dt>Funding Amount</dt>
                        <dd>{{ object.funding_amount }}</dd>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer d-none">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <a href='{% url "funder_delete" object.funder_id %}' class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Display program list -->
<div class="card">
    <div class="card-header bg-info text-white">
        <div class="col-md-10">
            <h5> Programs funded by {{object.organization_name}}</h5>
        </div>

        <div class="col-md-2">
            <a href='{% url "add_program" object.funder_id %}' class="pull-right"><button type="button" class="btn btn-light btn-sm"><i class="fa fa-plus"></i></button></a>
        </div>
    </div>
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-12" >
                    <table id="funder_program_list" class="table table-striped table-bordered table-row-clickable" width="100%">
                        <thead>
                        <tr>
                            <th>Program Name</th>
                            <th>Funding Amount</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block page_script %}
<script type="text/javascript">
     var table;

    /* Init datatable */
    var initDatatable = function($) {
        table = $("#funder_program_list").DataTable({
            "searching": true,
            "processing": true,
            "serverSide": false,
            "stateSave": true,
            "colReorder": true,
            "paging":true,
            "responsive": true,
            "ajax": {
                 "processing": true,
                 "url": '{% url "get_funder_program_list_for_datatable" object.funder_id %}',
                 "dataSrc": ""
             },
             "columns":[
                {data: 'fields.location_program_id'},

                {data: 'fields.funding_amount', className: "text-right", "width": "30%"},
             ]
        });
    };
    var onProgramRowClick = function () {
        var data = table.row( this ).data();

        var url = '/domain/program_view/'  + data.pk;
        appUtils.navigateToUrl(url);
    };

    /* init this page */
    var initProgramListView = function ($) {
        initDatatable($);

        // bind row click event
        // $('#funder_program_list tbody').on('click', 'tr', onProgramRowClick);
    };

    /* int this page */
    jQuery(document).ready(initProgramListView($));
</script>
{% endblock %}

code_base/funders/templates/funder_list.html
{% extends 'home.html' %}

{% block page-title %}
Funder List
{% endblock %}
 {% block page-title-path %}
<ol class="breadcrumb text-right">
    <li class="active">Funders</li>
</ol>
{% endblock %}
{% block right-pane-content %}

<!--Right panel - start here -->

<div class="card">
    <div class="card-header bg-info text-white">
        <div class="col-md-10">
            <h5 class="card-title">Funders</h5>
        </div>
        <div class="col-md-2">
            <a href="{% url 'funder_create' %}" class="pull-right"><button type="button" class="btn btn-light btn-sm"><i class="fa fa-plus"></i></button></a>
        </div>
    </div>
    <div class="card-body">
        <table id="funder_list" class="table table-striped table-bordered table-row-clickable" width="100%">
            <thead>
            <tr>
                <th>Funding Organization</th>
                <th>Date of Funding</th>
                <th>Funding Amount(in INR)</th>

            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
</div>
<!-- Right panel - ends here -->

{% endblock %}


{% block page_script %}
<script type="text/javascript">
    var table;
    /* Init datatable */
    var initDatatable = function($) {
        table = $("#funder_list").DataTable({
            "searching": true,
            "processing": true,
            "serverSide": false,
            "1stateSave": true,
            "colReorder": true,
            "paging":true,
            "responsive": true,
            "ajax": {
                 "processing": true,
                 "url": '{% url "get_funder_list_for_datatable" %}',
                 "dataSrc": ""
             },
            "columns":[
                {data: 'fields.organization_name'},
                {data: 'fields.funding_date', render: appUtils.formatDatatableDate },
                {data: 'fields.funding_amount', className: "text-right", "width": "25%"},
            ]
        });
    };
    var onFunderRowClick = function () {
        var data = table.row( this ).data();
        var url = 'view/' + data.pk;
        appUtils.navigateToUrl(url);
    };

     /* init this page */
    var initFunderListView = function ($) {
        initDatatable($);
        // bind row click event
        $('#funder_list tbody').on('click', 'tr', onFunderRowClick);
    };


    /* int this page */
    jQuery(document).ready(initFunderListView($));

</script>
{% endblock %}